PROGRAM ex2
IMPLICIT NONE
REAL, PARAMETER :: PI = 3.14159265
CHARACTER(LEN=11), PARAMETER :: FILENAME_INPUT = 'radians.dat'
IF (INQUIRE(FILE=FILENAME_INPUT)) THEN
    OPEN(UNIT=20, FILE=FILENAME_INPUT, STATUS='OLD', ACCESS='DIRECT', FORM='FORMATTED', ACTION='READ')
    ! MC not completed beacuse already implemented as subprogram.
ELSE
    WRITE (*,*) 'File does not exist'
END IF
END PROGRAM ex2
